export const TEA_OR_COFFEE_WORDS = [
  'Praia',
  'Montanha',
  'Acampamento',
  'Parque de diversões',
  'Viagem de avião',
  'Festa surpresa',
  'Cinema',
  'Biblioteca',
  'Churrasco',
  'Piquenique',
  'Videogame',
  'Karaokê',
  'Bicicleta',
  'Skate',
  'Guarda-chuva',
  'Fone de ouvido',
  'Câmera fotográfica',
  'Controle remoto',
  'Relógio de pulso',
  'Mochila',
  'Castelo',
  'Foguete',
  'Ilha deserta',
  'Arco-íris',
  'Cachoeira',
  'Floresta',
  'Tempestade',
  'Astronauta',
  'Dinossauro',
  'Dragão',
  'Capivara',
  'Pinguim',
  'Girafa',
  'Tubarão',
  'Pizza',
  'Brigadeiro',
  'Pão de queijo',
  'Pipoca',
  'Sorvete',
  'Abacaxi',
  'Violão',
  'Bateria',
  'Microfone',
  'Piano',
  'Super-herói',
  'Detetive',
  'Professor',
  'Piloto de corrida',
] as const;
