import { GameDefinition } from '../core/game-engine/game-definition';

export const GAME_CATALOG = [
  {
    id: 'who-am-i',
    slug: 'quem-sou-eu',
    name: 'Quem Sou Eu',
    shortDescription: 'Uma identidade na tela. Perguntas na roda. Adivinhe quem você é.',
    fullDescription:
      'O Mesa sorteia uma identidade e prepara a tela para que o grupo veja. Quem está jogando faz perguntas de sim ou não até descobrir quem é.',
    players: { min: 2, max: 20 },
    estimatedMinutes: 10,
    categories: ['Adivinhação'],
    complexity: 'easy',
    deviceMode: 'single-device',
    vibe: ['leve', 'rápido', 'quebra-gelo'],
    goodFor: ['amigos', 'família', 'grupos novos'],
    engine: 'identity-reveal',
    features: ['countdown', 'audio', 'haptics'],
    availability: 'available',
    accent: '#EF4444',
    instructions: [
      'Comece a rodada e posicione o celular sem olhar a identidade.',
      'O grupo responde apenas “sim” ou “não” às suas perguntas.',
      'Quando adivinhar — ou quiser trocar — comece uma nova rodada.',
    ],
    appResponsibility:
      'O Mesa sorteia e revela a identidade. Perguntas, respostas e acertos ficam com a roda.',
  },
  {
    id: 'tea-or-coffee',
    slug: 'cha-ou-cafe',
    name: 'Chá ou Café',
    shortDescription: 'Uma palavra secreta e escolhas entre duas opções para chegar cada vez mais perto.',
    fullDescription:
      'Uma pessoa recebe uma palavra secreta. O resto da Mesa cria perguntas com duas opções e tenta descobrir o segredo pelas escolhas.',
    players: { min: 2, max: 20 },
    estimatedMinutes: 10,
    categories: ['Conversa', 'Adivinhação'],
    complexity: 'easy',
    deviceMode: 'single-device',
    vibe: ['leve', 'conversa', 'criativo'],
    goodFor: ['amigos', 'família', 'quebra-gelo'],
    engine: 'comparison-reveal',
    features: ['countdown', 'audio', 'haptics'],
    availability: 'available',
    accent: '#27B89A',
    instructions: [
      'Uma pessoa revela a palavra secreta sem mostrar para a roda.',
      'Comecem com “Chá ou café?” e continuem criando perguntas com duas opções.',
      'Quem conhece a palavra escolhe sempre a opção que considera mais próxima do segredo.',
    ],
    appResponsibility: 'O Mesa sorteia e protege a palavra. Comparações, escolhas e tentativas acontecem na conversa.',
    example: ['Chá ou café?', 'Praia ou montanha?', 'Dia ou noite?'],
  },
  {
    id: 'ito',
    slug: 'ito',
    name: 'Ito',
    shortDescription: 'Dicas subjetivas, números secretos e uma missão: entrar na mesma sintonia.',
    fullDescription:
      'Cada pessoa recebe um número de 1 a 100 e dá uma dica dentro de uma escala. A mesa tenta ordenar as dicas sem conhecer os números.',
    players: { min: 2, max: 12 },
    estimatedMinutes: 15,
    categories: ['Cooperativo'],
    complexity: 'medium',
    deviceMode: 'single-device',
    vibe: ['criativo', 'cooperativo', 'conversa'],
    goodFor: ['amigos próximos', 'grupos criativos'],
    engine: 'scale-ordering',
    features: ['private-reveal', 'player-setup'],
    availability: 'available',
    accent: '#3B82F6',
    instructions: [
      'Cada pessoa recebe um número secreto entre 1 e 100.',
      'Dê uma dica que represente sua posição na escala da rodada.',
      'Em grupo, organizem as dicas antes de revelar os números.',
    ],
    appResponsibility: 'O Mesa distribui números e propõe a escala. A conversa e a ordem são do grupo.',
  },
  {
    id: 'impostor',
    slug: 'impostor',
    name: 'Impostor',
    shortDescription: 'Palavras, pistas e uma pessoa fora de sintonia. Será que ela sabe?',
    fullDescription:
      'Informações privadas colocam uma ou mais pessoas fora de sintonia. Escolha se o impostor conhece seu papel ou também joga no escuro.',
    players: { min: 3, max: 12 },
    estimatedMinutes: 15,
    categories: ['Blefe', 'Dedução'],
    complexity: 'medium',
    deviceMode: 'single-device',
    vibe: ['blefe', 'suspeita', 'debate'],
    goodFor: ['grupos competitivos', 'festas'],
    engine: 'hidden-role',
    features: ['private-reveal', 'player-setup'],
    availability: 'available',
    accent: '#A855F7',
    instructions: [
      'Passe o celular para cada pessoa revelar sua informação.',
      'Dê uma pista relacionada ao segredo sem ser óbvio demais.',
      'Debatam e votem em quem parece estar improvisando.',
    ],
    appResponsibility: 'O Mesa distribui as informações privadas. Pistas, debate e votação são presenciais.',
    modes: [
      { name: 'Clássico', description: 'O impostor sabe seu papel e pode ou não receber uma dica.' },
      { name: 'No escuro', description: 'Todos recebem uma palavra e ninguém sabe quem recebeu a diferente.' },
    ],
  },
  {
    id: 'hot-potato',
    slug: 'batata-quente',
    name: 'Batata Quente',
    shortDescription: 'Um tema, respostas rápidas e uma batata que pode explodir a qualquer momento.',
    fullDescription:
      'Digam itens relacionados ao tema e passem a vez sem perder tempo. Quando o relógio zerar, quem estiver com a batata perde a rodada.',
    players: { min: 2, max: 12 },
    estimatedMinutes: 5,
    categories: ['Agilidade'],
    complexity: 'easy',
    deviceMode: 'single-device',
    vibe: ['rápido', 'energético', 'improviso'],
    goodFor: ['amigos', 'família', 'festas'],
    engine: 'timed-turns',
    features: ['timer', 'audio', 'haptics', 'player-setup'],
    availability: 'available',
    accent: '#F06449',
    instructions: [
      'O Mesa sorteia um tema e inicia a contagem regressiva.',
      'Diga um item válido, toque em “Passei a vez” e entregue o celular.',
      'Quando o tempo acabar, perde quem estiver com a vez.',
    ],
    appResponsibility: 'Tema, tempo e turnos ficam com o Mesa. Vocês dizem as respostas e decidem presencialmente o que vale.',
  },
  {
    id: 'impostor-question',
    slug: 'pergunta-do-impostor',
    name: 'Pergunta do Impostor',
    shortDescription: 'Perguntas parecidas, respostas suspeitas e alguém tentando se encaixar.',
    fullDescription:
      'Todo mundo recebe uma pergunta. Algumas pessoas recebem uma diferente, mas ninguém sabe quem. Respondam em voz alta e encontrem quem está fora de sintonia.',
    players: { min: 3, max: 12 },
    estimatedMinutes: 10,
    categories: ['Blefe', 'Dedução'],
    complexity: 'easy',
    deviceMode: 'single-device',
    vibe: ['conversa', 'suspeita', 'leve'],
    goodFor: ['amigos', 'festas', 'grupos novos'],
    engine: 'question-pairs',
    features: ['private-reveal', 'player-setup'],
    availability: 'available',
    accent: '#E94B87',
    instructions: [
      'Cada pessoa revela em segredo a pergunta que recebeu.',
      'Todos respondem em voz alta, sem mostrar a tela.',
      'Comparem as respostas e descubram quem recebeu algo diferente.',
    ],
    appResponsibility: 'O Mesa sorteia e distribui as perguntas e revela os papéis no final. Respostas, debate e votação ficam com a roda.',
  },
] as const satisfies readonly GameDefinition[];

export function findGame(slug: string): GameDefinition | undefined {
  return GAME_CATALOG.find((game) => game.slug === slug);
}
