import { GameDefinition } from '../core/game-engine/game-definition';

export const GAME_CATALOG = [
  {
    id: 'who-am-i',
    slug: 'quem-sou-eu',
    name: 'Quem Sou Eu',
    shortDescription: 'Uma identidade na tela. Perguntas na roda. Adivinhe quem você é.',
    fullDescription:
      'O Mesa sorteia uma identidade e prepara a tela para que o grupo veja. Quem está jogando faz perguntas de sim ou não até descobrir quem é.',
    players: { min: 2, max: 20 },
    estimatedMinutes: 10,
    categories: ['Adivinhação'],
    complexity: 'easy',
    deviceMode: 'single-device',
    vibe: ['leve', 'rápido', 'quebra-gelo'],
    goodFor: ['amigos', 'família', 'grupos novos'],
    engine: 'identity-reveal',
    features: ['countdown', 'audio', 'haptics'],
    availability: 'available',
    accent: '#EF4444',
    instructions: [
      'Comece a rodada e posicione o celular sem olhar a identidade.',
      'O grupo responde apenas “sim” ou “não” às suas perguntas.',
      'Quando adivinhar — ou quiser trocar — comece uma nova rodada.',
    ],
    appResponsibility:
      'O Mesa sorteia e revela a identidade. Perguntas, respostas e acertos ficam com a roda.',
  },
  {
    id: 'tea-or-coffee',
    slug: 'cha-ou-cafe',
    name: 'Chá ou Café',
    shortDescription: 'Uma palavra secreta e escolhas entre duas opções para chegar cada vez mais perto.',
    fullDescription:
      'Uma pessoa recebe uma palavra secreta. O resto da Mesa cria perguntas com duas opções e tenta descobrir o segredo pelas escolhas.',
    players: { min: 2, max: 20 },
    estimatedMinutes: 10,
    categories: ['Conversa', 'Adivinhação'],
    complexity: 'easy',
    deviceMode: 'single-device',
    vibe: ['leve', 'conversa', 'criativo'],
    goodFor: ['amigos', 'família', 'quebra-gelo'],
    engine: 'comparison-reveal',
    features: ['countdown', 'audio', 'haptics'],
    availability: 'available',
    accent: '#27B89A',
    instructions: [
      'Uma pessoa revela a palavra secreta sem mostrar para a roda.',
      'Comecem com “Chá ou café?” e continuem criando perguntas com duas opções.',
      'Quem conhece a palavra escolhe sempre a opção que considera mais próxima do segredo.',
    ],
    appResponsibility: 'O Mesa sorteia e protege a palavra. Comparações, escolhas e tentativas acontecem na conversa.',
    example: ['Chá ou café?', 'Praia ou montanha?', 'Dia ou noite?'],
  },
  {
    id: 'ito',
    slug: 'ito',
    name: 'Ito',
    shortDescription: 'Dicas subjetivas, números secretos e uma missão: entrar na mesma sintonia.',
    fullDescription:
      'Cada pessoa recebe um número de 1 a 100 e dá uma dica dentro de uma escala. A mesa tenta ordenar as dicas sem conhecer os números.',
    players: { min: 2, max: 12 },
    estimatedMinutes: 15,
    categories: ['Cooperativo'],
    complexity: 'medium',
    deviceMode: 'single-device',
    vibe: ['criativo', 'cooperativo', 'conversa'],
    goodFor: ['amigos próximos', 'grupos criativos'],
    engine: 'scale-ordering',
    features: ['private-reveal', 'player-setup'],
    availability: 'available',
    accent: '#3B82F6',
    instructions: [
      'Cada pessoa recebe um número secreto entre 1 e 100.',
      'Dê uma dica que represente sua posição na escala da rodada.',
      'Em grupo, organizem as dicas antes de revelar os números.',
    ],
    appResponsibility: 'O Mesa distribui números e propõe a escala. A conversa e a ordem são do grupo.',
  },
  {
    id: 'impostor',
    slug: 'impostor',
    name: 'Impostor',
    shortDescription: 'Palavras, pistas e uma pessoa fora de sintonia. Será que ela sabe?',
    fullDescription:
      'Informações privadas colocam uma ou mais pessoas fora de sintonia. Escolha se o impostor conhece seu papel ou também joga no escuro.',
    players: { min: 3, max: 12 },
    estimatedMinutes: 15,
    categories: ['Blefe', 'Dedução'],
    complexity: 'medium',
    deviceMode: 'single-device',
    vibe: ['blefe', 'suspeita', 'debate'],
    goodFor: ['grupos competitivos', 'festas'],
    engine: 'hidden-role',
    features: ['private-reveal', 'player-setup'],
    availability: 'available',
    accent: '#A855F7',
    instructions: [
      'Passe o celular para cada pessoa revelar sua informação.',
      'Dê uma pista relacionada ao segredo sem ser óbvio demais.',
      'Debatam e votem em quem parece estar improvisando.',
    ],
    appResponsibility: 'O Mesa distribui as informações privadas. Pistas, debate e votação são presenciais.',
    modes: [
      { name: 'Clássico', description: 'O impostor sabe seu papel e pode ou não receber uma dica.' },
      { name: 'No escuro', description: 'Todos recebem uma palavra e ninguém sabe quem recebeu a diferente.' },
    ],
  },
  {
    id: 'hot-potato',
    slug: 'batata-quente',
    name: 'Batata Quente',
    shortDescription: 'Um tema, respostas rápidas e uma batata que pode explodir a qualquer momento.',
    fullDescription:
      'Digam itens relacionados ao tema e passem a vez sem perder tempo. Quando o relógio zerar, quem estiver com a batata perde a rodada.',
    players: { min: 2, max: 12 },
    estimatedMinutes: 5,
    categories: ['Agilidade'],
    complexity: 'easy',
    deviceMode: 'single-device',
    vibe: ['rápido', 'energético', 'improviso'],
    goodFor: ['amigos', 'família', 'festas'],
    engine: 'timed-turns',
    features: ['timer', 'audio', 'haptics', 'player-setup'],
    availability: 'available',
    accent: '#F06449',
    instructions: [
      'O Mesa sorteia um tema e inicia a contagem regressiva.',
      'Diga um item válido, toque em “Passei a vez” e entregue o celular.',
      'Quando o tempo acabar, perde quem estiver com a vez.',
    ],
    appResponsibility: 'Tema, tempo e turnos ficam com o Mesa. Vocês dizem as respostas e decidem presencialmente o que vale.',
  },
  {
    id: 'impostor-question',
    slug: 'pergunta-do-impostor',
    name: 'Pergunta do Impostor',
    shortDescription: 'Perguntas parecidas, respostas suspeitas e alguém tentando se encaixar.',
    fullDescription:
      'Todo mundo recebe uma pergunta. Algumas pessoas recebem uma diferente, mas ninguém sabe quem. Respondam em voz alta e encontrem quem está fora de sintonia.',
    players: { min: 3, max: 12 },
    estimatedMinutes: 10,
    categories: ['Blefe', 'Dedução'],
    complexity: 'easy',
    deviceMode: 'single-device',
    vibe: ['conversa', 'suspeita', 'leve'],
    goodFor: ['amigos', 'festas', 'grupos novos'],
    engine: 'question-pairs',
    features: ['private-reveal', 'player-setup'],
    availability: 'available',
    accent: '#E94B87',
    instructions: [
      'Cada pessoa revela em segredo a pergunta que recebeu.',
      'Todos respondem em voz alta, sem mostrar a tela.',
      'Comparem as respostas e descubram quem recebeu algo diferente.',
    ],
    appResponsibility: 'O Mesa sorteia e distribui as perguntas e revela os papéis no final. Respostas, debate e votação ficam com a roda.',
  },
  {
    id: 'location',
    slug: 'onde-estou',
    name: 'Onde Estou',
    shortDescription: 'Todo mundo conhece o lugar — menos quem precisa fingir que sabe.',
    fullDescription: 'Façam perguntas para descobrir quem está fora do lugar. No Clássico, o impostor conhece seu papel; no escuro, todo mundo acredita que recebeu o local verdadeiro.',
    players: { min: 3, max: 12 },
    estimatedMinutes: 15,
    categories: ['Blefe', 'Dedução'],
    complexity: 'medium',
    deviceMode: 'single-device',
    vibe: ['mistério', 'conversa', 'suspeita'],
    goodFor: ['amigos', 'festas', 'grupos competitivos'],
    engine: 'hidden-role',
    features: ['private-reveal', 'player-setup'],
    availability: 'available',
    accent: '#168F96',
    instructions: [
      'Cada pessoa revela em segredo se recebeu o local ou o papel de impostor.',
      'Façam perguntas uns aos outros sem entregar o lugar de graça.',
      'Descubram quem não sabe onde está antes que essa pessoa deduza o local.',
    ],
    appResponsibility: 'O Mesa conduz local, papéis, dicas, distribuição e resultado. Perguntas, respostas, acusações e a decisão de quem perdeu ficam com a Mesa.',
    modes: [
      { name: 'Clássico', description: 'O impostor sabe que não conhece o local e pode receber uma dica.' },
      { name: 'No escuro', description: 'Todo mundo recebe um local — mas algumas pessoas recebem um lugar diferente sem saber.' },
    ],
  },
  {
    id: 'contact', slug: 'contato', name: 'Contato',
    shortDescription: 'Uma palavra secreta, letras reveladas e conexões feitas em sintonia.',
    fullDescription: 'O mestre conhece uma palavra. A roda cria conexões para conquistar novas letras e chegar ao segredo.',
    players: { min: 3, max: 20 }, estimatedMinutes: 15, categories: ['Adivinhação', 'Cooperativo'], complexity: 'medium', deviceMode: 'single-device',
    vibe: ['vocabulário','sintonia','dedução'], goodFor: ['amigos','família'], engine: 'contact-word', features: ['countdown','audio','haptics','private-reveal'], availability: 'available', accent: '#A6BF3B',
    instructions: ['O mestre revela apenas a primeira letra da palavra.','A roda dá definições até duas pessoas fazerem Contato.','O mestre libera novas letras — ou bloqueia a conexão se descobrir a resposta antes.'],
    appResponsibility: 'O Mesa sorteia e protege a palavra. Dicas, contatos, bloqueios e a vitória acontecem presencialmente.',
  },
  {
    id: 'rating', slug: 'qual-e-a-nota', name: 'Qual é a Nota',
    shortDescription: 'Uma nota secreta, uma pista subjetiva e um teste de sintonia.',
    fullDescription: 'Uma pessoa recebe uma nota de 1 a 10 e dá uma pista dentro da escala proposta. O parceiro ou a roda tenta descobrir o valor.',
    players: { min: 2, max: 12 }, estimatedMinutes: 10, categories: ['Conversa','Adivinhação'], complexity: 'easy', deviceMode: 'single-device',
    vibe: ['sintonia','criativo','conversa'], goodFor: ['duplas','amigos'], engine: 'rating', features: ['private-reveal','player-setup'], availability: 'available', accent: '#5968D8',
    instructions: ['Escolham jogar em duplas ou uma pessoa contra todos.','Quem dá a pista revela em segredo uma nota de 1 a 10.','A pista deve combinar com o tema; o resto da Mesa tenta descobrir a nota.'],
    appResponsibility: 'O Mesa sorteia tema e notas. Pistas, palpites e a decisão de proximidade ficam com a roda.',
  },
  {
    id: 'word-list', slug: 'jogo-da-lista', name: 'Jogo da Lista',
    shortDescription: 'Uma lista secreta e muitas pistas para fazer a roda acertar.',
    fullDescription: 'Uma pessoa recebe uma lista de palavras e conduz a rodada com pistas. O grupo tenta completar a lista sem ver a tela.',
    players: { min: 2, max: 20 }, estimatedMinutes: 10, categories: ['Adivinhação'], complexity: 'easy', deviceMode: 'single-device',
    vibe: ['rápido','vocabulário','grupo'], goodFor: ['amigos','família'], engine: 'word-list', features: ['private-reveal'], availability: 'available', accent: '#E8794F',
    instructions: ['Escolham quantas palavras entram na rodada.','Só a pessoa que dá as pistas revela a lista.','O grupo tenta acertar todas; vocês decidem presencialmente o que vale.'],
    appResponsibility: 'O Mesa monta e protege a lista. Pistas, acertos e o encerramento são decididos pela roda.',
  },
  {
    id: 'letter-chain', slug: 'adivinhe-a-palavra', name: 'Adivinhe a Palavra',
    shortDescription: 'Acrescente uma letra, evite completar a palavra e saiba a hora de duvidar.',
    fullDescription: 'A partir de uma letra sorteada, a roda constrói uma palavra em sequência. Quem completar uma palavra perde — e qualquer pessoa pode desafiar uma sequência impossível.',
    players: { min: 2, max: 20 }, estimatedMinutes: 10, categories: ['Conversa','Adivinhação'], complexity: 'easy', deviceMode: 'single-device',
    vibe: ['vocabulário','rápido','desafio'], goodFor: ['amigos','família'], engine: 'letter-chain', features: [], availability: 'available', accent: '#38A889',
    instructions: ['O Mesa sorteia a primeira letra.','Cada pessoa acrescenta uma letra pensando em uma palavra válida.','Quem completar uma palavra perde. Diga “Duvido” se a sequência parecer impossível.'],
    appResponsibility: 'O Mesa escolhe o começo. Letras, desafios e validação das palavras acontecem presencialmente.',
  },
] as const satisfies readonly GameDefinition[];

export function findGame(slug: string): GameDefinition | undefined {
  return GAME_CATALOG.find((game) => game.slug === slug);
}
