import { ImpostorContent } from '../../core/game-engine/impostor/impostor.models';

export const IMPOSTOR_CONTENT: readonly ImpostorContent[] = [
  { word: 'Casa', classicHints: ['Moradia', 'Construção', 'Endereço'], blindWords: ['Sala', 'Apartamento'] },
  { word: 'Avião', classicHints: ['Aeroporto', 'Altitude', 'Viagem'], blindWords: ['Helicóptero', 'Planador'] },
  { word: 'Biblioteca', classicHints: ['Silêncio', 'Estante', 'Leitura'], blindWords: ['Livraria', 'Sala de estudos'] },
  { word: 'Cachorro', classicHints: ['Companhia', 'Passeio', 'Coleira'], blindWords: ['Gato', 'Lobo'] },
  { word: 'Café', classicHints: ['Aroma', 'Manhã', 'Cafeína'], blindWords: ['Chá', 'Chocolate quente'] },
  { word: 'Cinema', classicHints: ['Tela', 'Pipoca', 'Sessão'], blindWords: ['Teatro', 'Streaming'] },
  { word: 'Chuva', classicHints: ['Nuvem', 'Guarda-chuva', 'Previsão'], blindWords: ['Garoa', 'Tempestade'] },
  { word: 'Circo', classicHints: ['Picadeiro', 'Lona', 'Espetáculo'], blindWords: ['Parque de diversões', 'Teatro'] },
  { word: 'Deserto', classicHints: ['Calor', 'Areia', 'Oásis'], blindWords: ['Praia', 'Savana'] },
  { word: 'Elevador', classicHints: ['Prédio', 'Botão', 'Andar'], blindWords: ['Escada rolante', 'Teleférico'] },
  { word: 'Escola', classicHints: ['Recreio', 'Aula', 'Mochila'], blindWords: ['Universidade', 'Curso'] },
  { word: 'Foguete', classicHints: ['Espaço', 'Lançamento', 'Órbita'], blindWords: ['Satélite', 'Avião'] },
  { word: 'Floresta', classicHints: ['Árvores', 'Trilha', 'Natureza'], blindWords: ['Selva', 'Parque'] },
  { word: 'Geladeira', classicHints: ['Cozinha', 'Frio', 'Conservação'], blindWords: ['Freezer', 'Armário'] },
  { word: 'Hospital', classicHints: ['Plantão', 'Cuidado', 'Enfermaria'], blindWords: ['Clínica', 'Pronto-socorro'] },
  { word: 'Museu', classicHints: ['Exposição', 'História', 'Visita'], blindWords: ['Galeria', 'Biblioteca'] },
  { word: 'Navio', classicHints: ['Oceano', 'Porto', 'Convés'], blindWords: ['Balsa', 'Submarino'] },
  { word: 'Padaria', classicHints: ['Forno', 'Manhã', 'Balcão'], blindWords: ['Cafeteria', 'Confeitaria'] },
  { word: 'Pizza', classicHints: ['Fatia', 'Forno', 'Entrega'], blindWords: ['Lasanha', 'Esfiha'] },
  { word: 'Praia', classicHints: ['Litoral', 'Sol', 'Areia'], blindWords: ['Piscina', 'Ilha'] },
  { word: 'Robô', classicHints: ['Máquina', 'Programa', 'Automação'], blindWords: ['Androide', 'Computador'] },
  { word: 'Sorvete', classicHints: ['Doce', 'Frio', 'Verão'], blindWords: ['Picolé', 'Milk-shake'] },
  { word: 'Trem', classicHints: ['Trilho', 'Estação', 'Vagão'], blindWords: ['Metrô', 'Bonde'] },
  { word: 'Vulcão', classicHints: ['Lava', 'Cratera', 'Montanha'], blindWords: ['Gêiser', 'Terremoto'] },
] as const;
