import { ImpostorContent } from '../../core/game-engine/impostor/impostor.models';

export const IMPOSTOR_CONTENT: readonly ImpostorContent[] = [
  { word: 'Avião', hints: ['transporte', 'altura', 'viagem'] },
  { word: 'Biblioteca', hints: ['silêncio', 'estante', 'leitura'] },
  { word: 'Cachorro', hints: ['animal', 'companhia', 'passeio'] },
  { word: 'Café', hints: ['bebida', 'aroma', 'manhã'] },
  { word: 'Cinema', hints: ['tela', 'pipoca', 'sessão'] },
  { word: 'Chuva', hints: ['clima', 'nuvem', 'guarda-chuva'] },
  { word: 'Circo', hints: ['espetáculo', 'picadeiro', 'lona'] },
  { word: 'Deserto', hints: ['paisagem', 'calor', 'areia'] },
  { word: 'Elevador', hints: ['prédio', 'botão', 'andar'] },
  { word: 'Escola', hints: ['aprendizado', 'sala', 'recreio'] },
  { word: 'Foguete', hints: ['espaço', 'lançamento', 'velocidade'] },
  { word: 'Floresta', hints: ['natureza', 'árvores', 'trilha'] },
  { word: 'Geladeira', hints: ['cozinha', 'frio', 'comida'] },
  { word: 'Hospital', hints: ['saúde', 'cuidado', 'plantão'] },
  { word: 'Ilha', hints: ['mar', 'isolado', 'praia'] },
  { word: 'Janela', hints: ['casa', 'vista', 'vidro'] },
  { word: 'Museu', hints: ['exposição', 'história', 'visita'] },
  { word: 'Navio', hints: ['oceano', 'viagem', 'porto'] },
  { word: 'Padaria', hints: ['comida', 'manhã', 'forno'] },
  { word: 'Parque', hints: ['lazer', 'grama', 'passeio'] },
  { word: 'Pizza', hints: ['comida', 'fatia', 'forno'] },
  { word: 'Praia', hints: ['litoral', 'sol', 'areia'] },
  { word: 'Robô', hints: ['tecnologia', 'máquina', 'programação'] },
  { word: 'Sorvete', hints: ['doce', 'frio', 'verão'] },
  { word: 'Teatro', hints: ['palco', 'plateia', 'cena'] },
  { word: 'Tempestade', hints: ['clima', 'vento', 'trovão'] },
  { word: 'Trem', hints: ['trilho', 'estação', 'viagem'] },
  { word: 'Universidade', hints: ['estudo', 'campus', 'curso'] },
  { word: 'Vulcão', hints: ['natureza', 'lava', 'montanha'] },
  { word: 'Zoológico', hints: ['animais', 'visita', 'recintos'] },
] as const;
